'use client';
import { useState } from 'react';
import { api } from '../lib/api';
import type { BenchmarkItem, ExperimentConfig, ExperimentResult, ComparisonResult, SweepResult, RAGResponse, ExperimentFailureAnalysis } from '../types/api';
import { Answer, ComparisonTable, ExperimentView, Json, MetricCards, value } from './results';
type Mode = 'dashboard'|'query'|'experiments'|'comparisons'|'sweeps'|'failure-analysis';
const initial: ExperimentConfig = {experiment_name:'',benchmark_name:'',model:'kr/claude-sonnet-4.5',retrieval_strategy:'dense',top_k:5,candidate_k:20,reranker_enabled:false,query_rewrite_enabled:false};
const titles:Record<Mode,[string,string]> = {dashboard:['Research overview','Load an experiment to inspect quality, retrieval and resource usage.'],query:['Query workspace','Ask a question and inspect the evidence behind the answer.'],experiments:['Experiments','Run a controlled benchmark or inspect a saved experiment.'],comparisons:['Strategy comparisons','Compare recorded metrics across configurations on the same benchmark.'],sweeps:['Parameter sweeps','Study top-k sensitivity while keeping the base configuration fixed.'],'failure-analysis':['Failure analysis','Trace recorded failures across retrieval, generation, citations and refusal behavior.']};
function ConfigForm({config,onChange}:{config:ExperimentConfig;onChange:(c:ExperimentConfig)=>void}) {return <div className="form-grid">{(['experiment_name','benchmark_name','model'] as const).map(k => <label key={k}>{k.replaceAll('_',' ')}<input required value={config[k]} onChange={e=>onChange({...config,[k]:e.target.value})}/></label>)}<label>Retrieval strategy<select value={config.retrieval_strategy} onChange={e=>onChange({...config,retrieval_strategy:e.target.value as ExperimentConfig['retrieval_strategy']})}>{['dense','bm25','hybrid'].map(s=><option key={s}>{s}</option>)}</select></label>{(['top_k','candidate_k'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type="number" min="1" step="1" required value={config[k]??''} onChange={e=>onChange({...config,[k]:e.target.valueAsNumber})}/></label>)}{(['reranker_enabled','query_rewrite_enabled'] as const).map(k=><label className="check" key={k}><input type="checkbox" checked={config[k]??false} onChange={e=>onChange({...config,[k]:e.target.checked})}/>{k.replaceAll('_',' ')}</label>)}</div>;}
function benchmark(text:string):BenchmarkItem[]{let parsed:unknown;try{parsed=JSON.parse(text);}catch{throw new Error('Benchmark must be valid JSON.');}if(!Array.isArray(parsed)||!parsed.length)throw new Error('Provide a non-empty JSON array of benchmark items.');return parsed as BenchmarkItem[];}
export function Workspace({mode}:{mode:Mode}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[id,setId]=useState(''),[question,setQuestion]=useState(''),[topK,setTopK]=useState(5);
 const [config,setConfig]=useState(initial),[configs,setConfigs]=useState<ExperimentConfig[]>([initial,{...initial,retrieval_strategy:'bm25'}]);
 const [bench,setBench]=useState(''),[values,setValues]=useState('1, 3, 5, 10');
 const [experiment,setExperiment]=useState<ExperimentResult>(),[comparison,setComparison]=useState<ComparisonResult>(),[sweep,setSweep]=useState<SweepResult>(),[answer,setAnswer]=useState<RAGResponse>(),[analysis,setAnalysis]=useState<ExperimentFailureAnalysis>();
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');setExperiment(undefined);setComparison(undefined);setSweep(undefined);setAnswer(undefined);setAnalysis(undefined);try{await action();}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
 async function load(){await perform(async()=>{if(mode==='comparisons')setComparison(await api.comparison(id));else if(mode==='sweeps')setSweep(await api.sweep(id));else if(mode==='failure-analysis')setAnalysis(await api.analysis(id));else setExperiment(await api.experiment(id));});}
 async function run(){await perform(async()=>{if(mode==='query'){setAnswer(await api.query(question.trim(),topK));return;}const items=benchmark(bench);if(mode==='experiments')setExperiment(await api.runExperiment({benchmark:items,config}));if(mode==='comparisons')setComparison(await api.runComparison({benchmark:items,configs}));if(mode==='sweeps'){const ks=values.split(',').map(x=>Number(x.trim()));if(ks.some(k=>!Number.isInteger(k)||k<=0)||new Set(ks).size!==ks.length)throw new Error('Top-k values must be unique positive integers, separated by commas.');setSweep(await api.runSweep({benchmark:items,base_config:config,sweep_type:'top_k',values:ks}));}});}
 return <div className="workspace"><header><div className="eyebrow">EVALUATION LAB / {mode==='dashboard'?'OVERVIEW':mode.toUpperCase().replaceAll('-',' ')}</div><h1>{titles[mode][0]}</h1><p>{titles[mode][1]}</p></header>
 {mode!=='query'&&<form className="panel load-form" onSubmit={e=>{e.preventDefault();void load();}}><label>{mode==='comparisons'?'Comparison':mode==='sweeps'?'Sweep':'Experiment'} ID<input required placeholder="Paste a saved result UUID" value={id} onChange={e=>setId(e.target.value)}/></label><button disabled={busy}>{mode==='failure-analysis'?'Analyze failures':'Load saved result'} <span>↗</span></button></form>}
 {['query','experiments','comparisons','sweeps'].includes(mode)&&<form className="panel" onSubmit={e=>{e.preventDefault();void run();}}><fieldset disabled={busy}><div className="section-heading"><h2>{mode==='query'?'Ask your corpus':'Configure a run'}</h2><span className="tag">{mode==='query'?'EVIDENCE FIRST':'EXPLICIT CONFIGURATION'}</span></div>
 {mode==='query'?<><label>Question<textarea required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like to know?"/></label><label className="short">Top-k<input required type="number" min="1" step="1" value={topK} onChange={e=>setTopK(e.target.valueAsNumber)}/></label></>:<>
 {mode==='comparisons'?<>{configs.map((c,i)=><section className="config-block" key={i}><div className="section-heading"><h3>Configuration {i+1}</h3>{configs.length>2&&<button type="button" className="secondary" onClick={()=>setConfigs(configs.filter((_,j)=>i!==j))}>Remove</button>}</div><ConfigForm config={c} onChange={v=>setConfigs(configs.map((x,j)=>i===j?v:x))}/></section>)}<button type="button" className="secondary" onClick={()=>setConfigs([...configs,{...configs[0]}])}>+ Add configuration</button><p className="hint">Benchmark name and model must match across configurations.</p></>:<ConfigForm config={config} onChange={setConfig}/>}
 {mode==='sweeps'&&<><label>Top-k values<input required value={values} onChange={e=>setValues(e.target.value)}/></label><p className="notice">Chunk-size sweeps are not available through HTTP yet.</p></>}
 <label>Benchmark items · JSON<textarea className="json-input" required value={bench} onChange={e=>setBench(e.target.value)} placeholder='[{"question_id":"...","question":"...","ground_truth":"...","answerable":true,"relevant_chunk_ids":["..."],"category":"factual","difficulty":"easy"}]'/></label><p className="hint">Use your existing benchmark data. Categories: factual, definition, comparison, multi_hop, reasoning, unanswerable. Difficulty: easy, medium, hard.</p>
 </>}<div className="form-actions"><span className="hint">{mode==='query'?'Uses configured backend services.':'Runs may take time and incur provider usage.'}</span><button>{busy?'Working…':mode==='query'?'Generate answer':'Run '+mode} <span>→</span></button></div></fieldset></form>}
 {busy&&<p role="status" className="notice">Request in progress. Waiting for the backend…</p>}{error&&<div role="alert" className="error"><strong>Request could not complete</strong><p>{error}</p></div>}
 {mode==='dashboard'&&!experiment&&<><div className="empty"><div className="empty-icon">≡</div><h2>No experiment loaded</h2><p>Load a saved experiment above to populate this overview.<br/>Only recorded measurements will appear here.</p></div><MetricCards/></>}
 {experiment&&<ExperimentView result={experiment}/>} {answer&&<Answer result={answer}/>}
 {comparison&&<section className="panel"><h2>Comparison results</h2><code>{comparison.comparison_id}</code><p>{comparison.benchmark_name} · {comparison.model}</p><ComparisonTable rows={comparison.metrics.map((m,i)=>({id:m.experiment_id,label:`${comparison.configs[i].retrieval_strategy} · k=${comparison.configs[i].top_k??5}`,summary:m.summary}))}/><Json data={comparison.configs}/></section>}
 {sweep&&<section className="panel"><h2>{sweep.sweep_type} sweep results</h2><code>{sweep.sweep_id}</code><ComparisonTable rows={sweep.experiments.map(e=>({id:e.experiment_id,label:`${sweep.sweep_type} = ${e.parameter_value}`,summary:e.summary}))}/><Json data={sweep.base_config}/></section>}
 {analysis&&<section className="panel"><h2>Failure analysis</h2><code>{analysis.experiment_id}</code><div className="metrics">{Object.entries({Analyzed:analysis.summary.total_questions_analyzed,'With failures':analysis.summary.questions_with_failures,'Failure-free':analysis.summary.failure_free_questions}).map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="hint">Rates use all analyzed questions. Categories may overlap. No detected failure does not prove success when metrics are missing.</p><div className="table-wrap"><table><thead><tr><th>Category</th><th>Count</th><th>Rate</th></tr></thead><tbody>{Object.entries(analysis.summary.category_counts).map(([k,n])=><tr key={k}><th>{k.replaceAll('_',' ')}</th><td><div className="bar" style={{width:`${analysis.summary.total_questions_analyzed?n/analysis.summary.total_questions_analyzed*100:0}%`}}/>{n}</td><td>{value(analysis.summary.category_rates[k])}</td></tr>)}</tbody></table></div><h3>Per-question diagnostics</h3>{analysis.questions.map(q=><details key={q.question_id}><summary>{q.question_id} · {q.failure_categories.join(', ')||'No detected failures'}</summary><ul>{q.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></details>)}</section>}
 </div>;
}
